name: implicit-weight-field
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13.0
  - torchvision=0.14.0
  - cudatoolkit=11.6
  - numpy=1.21.*
  - scipy=1.7.*
  - scikit-learn=1.0.*
  - matplotlib=3.5.*
  - seaborn=0.11.*
  - pandas=1.3.*
  - jupyter=1.0.*
  - ipykernel=6.9.*
  - pip=21.2.*
  - pip:
    - wandb>=0.12.0
    - tensorboard>=2.8.0
    - transformers>=4.25.0
    - optuna>=3.0.0
    - plotly>=5.5.0
    - pytest>=7.0.0
    - pytest-cov>=3.0.0
    - pyyaml>=6.0
    - click>=8.0.0
    - python-dotenv>=0.19.0
    - black>=22.0.0
    - flake8>=4.0.0
    - isort>=5.10.0
    - mypy>=0.910